#!/bin/bash

####################
# SBATCH OPTIONS
####################
#SBATCH --job-name=isol_db             # job name for queue, default may be u$
#SBATCH --partition=skx                 # see Stampede3 queues for guide (skx/skx-dev/icx...)
#SBATCH --error=isol_db.err                 # error file, default if empty is slurm$
#SBATCH --output=isol_db.out                # standard out file, no default
#SBATCH --time=2:00:00                 # hours:minutes:seconds
#SBATCH --nodes=1                      # only use 1 node, MPI option
#SBATCH --ntasks=1                     # how many tasks to start
#SBATCH --cpus-per-task=1              # number of cores to use, multi-core/mu$
#SBATCH --mail-user=hgp297@tacc.utexas.edu
#SBATCH --mail-type=all					# send email at beginning and end of job
#SBATCH -A DS-TracyBecker				# allocation name (if more than 1)
####################
# What to run
####################

pwd
date

# move all file from $WORK to $SCRATCH
cp -rf ./* $SCRATCH/isol-sys-database/

# cd into scratch
cd $SCRATCH/isol-sys-database/src/

pwd

# launch serial code
python ./main.py

# copy results back to $WORK
cp -rf ../data/* $WORK/isol-sys-database/data/
